---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: delugevpn
  name: delugevpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delugevpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: delugevpn
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tpu
                operator: NotIn
                values:
                - "true"
      containers:
        - name: delugevpn
          image: binhex/arch-delugevpn:latest
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          resources:
            requests:
              ephemeral-storage: "2Gi"
            limits:
              ephemeral-storage: "4Gi"
          env:
            - name: PUID
              value: "222"
            - name: PGID
              value: "321"
            - name: UMASK_SET
              value: "002"
            - name: TZ
              value: "America/Denver"
            - name: DELUGE_LOGLEVEL
              value: "error"
            - name: DELUGE_WEB_LOG_LEVEL
              value: "error"
            - name: DEBUG
              value: "false"
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_PROV
              value: "airvpn"
            - name: VPN_CLIENT
              value: "openvpn"
            - name: STRICT_PORT_FORWARD
              value: "no"
            - name: ENABLE_PRIVOXY
              value: "no"
            - name: LAN_NETWORK
              value: "192.168.0.0/24"
          ports:
            - containerPort: 12049
              name: inbound-tcp
              protocol: TCP
            - containerPort: 12049
              name: inbound-udp
              protocol: UDP
          volumeMounts:
            - name: k8s-pv02
              mountPath: /config
              subPath: deluge/config
            - name: k8s-pv02
              mountPath: /downloads
              subPath: deluge/downloads
            - name: data
              mountPath: /data/torrents
              subPath: torrents
      volumes:
        - name: k8s-pv02
          persistentVolumeClaim:
            claimName: synology-k8s-pv02
        - name: data
          persistentVolumeClaim:
            claimName: synology-data
