---
apiVersion: v1
kind: Service
metadata:
  name: delugevpn
spec:
  type: NodePort
  selector:
    app: delugevpn
  ports:
    - name: deluge-http
      port: 8112
      protocol: TCP
      targetPort: 8112
    - name: incoming-tcp
      port: 12022
      protocol: TCP
      targetPort: 12022
    - name: incoming-udp
      port: 12022
      protocol: UDP
      targetPort: 12022
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222
    - 192.168.0.223
