---
apiVersion: v1
kind: Service
metadata:
  name: delugevpn
spec:
  type: NodePort
  selector:
    app: delugevpn
  ports:
    - name: deluge-http
      port: 8112
      protocol: TCP
      targetPort: 8112
    - name: incoming-tcp
      port: 12049
      protocol: TCP
      targetPort: 12049
    - name: incoming-udp
      port: 12049
      protocol: UDP
      targetPort: 12049
  externalIPs:
    - 192.168.0.211
    - 192.168.0.221
    - 192.168.0.222
    - 192.168.0.223
    - 192.168.0.224
