apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proxmox-deluge-temp
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: proxmox
  resources:
    requests:
      storage: 100Gi
