---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: delugevpn
  name: delugevpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delugevpn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: delugevpn
    spec:
      containers:
        - name: delugevpn
          image: binhex/arch-delugevpn:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          env:
            - name: PUID
              value: "222"
            - name: PGID
              value: "321"
            - name: UMASK_SET
              value: "002"
            - name: TZ
              value: "America/Denver"
            - name: DELUGE_LOGLEVEL
              value: "error"
            - name: DELUGE_WEB_LOG_LEVEL
              value: "error"
            - name: DEBUG
              value: "false"
            - name: VPN_ENABLED
              value: "yes"
            - name: VPN_USER
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: "username"
            - name: VPN_PASS
              valueFrom:
                secretKeyRef:
                  name: vpn-credentials
                  key: "password"
            - name: VPN_PROV
              value: "airvpn"
            - name: VPN_CLIENT
              value: "openvpn"
            - name: ADDITIONAL_PORTS
              value: "12028"
            - name: STRICT_PORT_FORWARD
              value: "no"
            - name: ENABLE_PRIVOXY
              value: "no"
            - name: LAN_NETWORK
              value: "192.168.0.1/24"
          ports:
            - containerPort: 12028
              name: inbound-tcp
              protocol: TCP
            - containerPort: 12028
              name: inbound-udp
              protocol: UDP
          volumeMounts:
            - name: k8s-pv01
              mountPath: /config
              subPath: deluge/config
            - name: k8s-pv01
              mountPath: /downloads
              subPath: deluge/downloads
            - name: data
              mountPath: data/torrents
      volumes:
        - name: k8s-pv01
          persistentVolumeClaim:
            claimName: synology-k8s-pv01
        - name: data
          persistentVolumeClaim:
            claimName: synology-data
