apiVersion: v1
kind: PersistentVolume
metadata: 
  name: proxmox-deluge-temp
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: proxmox.home 
    path: "/var/deluge-temp"
