apiVersion: v1
kind: PersistentVolume
metadata: 
  name: synology-5tb
spec:
  capacity:
    storage: 5000Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-5tb
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.0.2
    path: "/volume1/k8s-pv01"
